/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eiji' at '15/09/10 12:36' with Gradle 2.6
 *
 * @author eiji, @date 15/09/10 12:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
